<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/automl/v1beta1/ranges.proto

namespace GPBMetadata\Google\Cloud\Automl\V1Beta1;

class Ranges
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e020a28676f6f676c652f636c6f75642f6175746f6d6c2f7631626574" .
            "61312f72616e6765732e70726f746f121b676f6f676c652e636c6f75642e" .
            "6175746f6d6c2e7631626574613122290a0b446f75626c6552616e676512" .
            "0d0a057374617274180120012801120b0a03656e64180220012801429101" .
            "0a1f636f6d2e676f6f676c652e636c6f75642e6175746f6d6c2e76316265" .
            "746131420b52616e67657350726f746f50015a41676f6f676c652e676f6c" .
            "616e672e6f72672f67656e70726f746f2f676f6f676c65617069732f636c" .
            "6f75642f6175746f6d6c2f763162657461313b6175746f6d6cca021b476f" .
            "6f676c655c436c6f75645c4175746f4d6c5c56316265746131620670726f" .
            "746f33"
        ), true);

        static::$is_initialized = true;
    }
}

